<?php
include '../model/conn.php';
/**
* Classe de base para scripts php
* Esta classe contem todas as funcionalidades de base para as outras classes herdeiras
* Encontra-se aqui, notadamente a conexao a base de dados
*/
class settings{

    function __construct() {
        self::attribute_cookie_to_session();
    }

    //var to paginate
    var $limit_per_page = 100;
    var $error_login = "";
    var $dir_item_pics = "../admin/uploads/";
    var $fone = "(17) 3325 3526";
    var $horario = "de segunda à sexta-feira, das 8:00 às 18:00";
    var $creditos_teste = 1; //quantidade de creditos a ser descontada ao enviar um teste
    var $creditos_ativar_usuario = 5; //quantidade de creditos inicial para um novo cliente
    var $dias_de_prazo_pagamento = 7; //dias de prazo para pagamento de boleto
    var $taxa_boleto = 0; //taxa de pagamento de boleto (cobrar do cliente)

    public function easyPrint($array, $die = 0) {
		print "<pre>";
		print_r($array);
		print "</pre>";	
        $die == 1 ? die() : "";
	} 
	

	public function paginate($array, $current) {
		$qty_items  = sizeof($array);
		$division   = $qty_items / $this->limit_per_page;
		$qty_pages  = is_integer($division) ? $division : ceil($division);
		$start      = $current == 1 ? 0 : ($current - 1) * $this->limit_per_page;
		$end        = ($qty_items - $start) > $this->limit_per_page ? $this->limit_per_page : ($qty_items - $start);
		$return[]   = array_slice($array, $start, $end);
		$return[]   = $qty_pages;
		return $return;
	}
	

	public function paginate_new($total_pages, $current) {
		$qty_items  = $total_pages;
		$division   = $qty_items / $this->limit_per_page;
		$qty_pages  = is_integer($division) ? $division : ceil($division);
		$start      = $current == 1 ? 0 : ($current - 1) * $this->limit_per_page;
		$end        = ($qty_items - $start) > $this->limit_per_page ? $this->limit_per_page : ($qty_items - $start);
		$return     = $qty_pages;
		return $return;
	}


    public function attribute_cookie_to_session() {
    }



    public function envia_erro_sql($funcao, $sql) {
    $message  = "
                TORPEDO CERTO - Sistema de Marketing por SMS
                ================================================================================
                \n
                INFORMATIVO DE ERRO TECNICO EM FUNÇÃO SQL
                -----------------------------------------
                \n
                Cliente........: ".$_SESSION['login']['razao_social']." - ID: ".$_SESSION['login']['id']."
                Nome da Função.: ".$funcao."
                SQL............: ".$sql."
                \n
                Equipe Torpedo Certo";
    /// enviar email pro fornecedor
    $email_to      = 'torpedocerto@gmail.com';
    $email_subject = "TorpedoCerto - ERRO TECNICO";
    self::send_mail($email_to, $email_subject, $message);
    self::cria_mensagem_erro($funcao, $sql);
    }


    public function cria_mensagem_erro($funcao, $sql) {
    $erro .= '<div style="border: solid 1px red;">';
    $erro .= '  <span style="font-size: 20px; color: red">TORPEDO CERTO INFORMA:</span>';
    $erro .= '  <ul>';
    $erro .= '    <li>Ocorreu um erro.</li>';
    $erro .= '    <li>Esta não é sua culpa, mas nossa.</li>';
    $erro .= '    <li>Nós fomos imediatamente alertados. Isso significa que nós podemos analisar e corrigir esse erro o mais rapidamente possível.</li>';
    $erro .= '    <li>Tente novamente mais tarde. Se o problema persistir, entre em contato conosco.</li>';
    if ($_SERVER['HTTP_HOST'] == 'dev.torpedo.lan') {
      $erro .= '<li>'.$funcao.'</li>';
      $erro .= '<li>'.$sql.'</li>';
    }
    $erro .= '  </ul>';
    $erro .= '</div>';
    die($erro);
    }

    
// Function to eliminate any caracter different to letters and numbers
	public function slug($label) {
		$slug=strtolower($label);
		$slug=str_replace('(',' ',$slug);
		$slug=str_replace(')',' ',$slug);
		$slug=str_replace('/',' ',$slug);
		$slug=str_replace('-',' ',$slug);
		$slug=str_replace('À','a',$slug);
		$slug=str_replace('Á','a',$slug);
		$slug=str_replace('Â','a',$slug);
		$slug=str_replace('Ã','a',$slug);
		$slug=str_replace('Ä','a',$slug);
		$slug=str_replace('Å','a',$slug);
		$slug=str_replace('à','a',$slug);
		$slug=str_replace('á','a',$slug);
		$slug=str_replace('â','a',$slug);
		$slug=str_replace('ã','a',$slug);
		$slug=str_replace('ä','a',$slug);
		$slug=str_replace('å','a',$slug);
		$slug=str_replace('Ò','o',$slug);
		$slug=str_replace('Ó','o',$slug);
		$slug=str_replace('Ô','o',$slug);
		$slug=str_replace('Õ','o',$slug);
		$slug=str_replace('Ö','o',$slug);
		$slug=str_replace('Ø','o',$slug);
		$slug=str_replace('ò','o',$slug);
		$slug=str_replace('ó','o',$slug);
		$slug=str_replace('ô','o',$slug);
		$slug=str_replace('õ','o',$slug);
		$slug=str_replace('ö','o',$slug);
		$slug=str_replace('ø','o',$slug);
		$slug=str_replace('È','e',$slug);
		$slug=str_replace('É','e',$slug);
		$slug=str_replace('Ê','e',$slug);
		$slug=str_replace('Ë','e',$slug);
		$slug=str_replace('è','e',$slug);
		$slug=str_replace('é','e',$slug);
		$slug=str_replace('ê','e',$slug);
		$slug=str_replace('ë','e',$slug);
		$slug=str_replace('Ç','c',$slug);
		$slug=str_replace('ç','c',$slug);
		$slug=str_replace('Ì','i',$slug);
		$slug=str_replace('Í','i',$slug);
		$slug=str_replace('Î','i',$slug);
		$slug=str_replace('Ï','i',$slug);
		$slug=str_replace('ì','i',$slug);
		$slug=str_replace('í','i',$slug);
		$slug=str_replace('î','i',$slug);
		$slug=str_replace('ï','i',$slug);
		$slug=str_replace('Ù','u',$slug);
		$slug=str_replace('Ú','u',$slug);
		$slug=str_replace('Û','u',$slug);
		$slug=str_replace('Ü','u',$slug);
		$slug=str_replace('ù','u',$slug);
		$slug=str_replace('ú','u',$slug);
		$slug=str_replace('û','u',$slug);
		$slug=str_replace('ü','u',$slug);
		$slug=str_replace('ÿ','y',$slug);
		$slug=str_replace('Ñ','n',$slug);
		$slug=str_replace('ñ','n',$slug);
		$slug=str_replace('Č','c',$slug);
		$slug=str_replace('é','e',$slug);
		$slug=str_replace('ß','s',$slug);
		$slug=str_replace('!',' ',$slug);
		$slug=str_replace('"',' ',$slug);
		$slug=str_replace('#',' ',$slug);
		$slug=str_replace('$',' ',$slug);
		$slug=str_replace('%',' ',$slug);
		$slug=str_replace('&',' ',$slug);
		$slug=str_replace("'",' ',$slug);
		$slug=str_replace('(',' ',$slug);
		$slug=str_replace(')',' ',$slug);
		$slug=str_replace('*',' ',$slug);
		$slug=str_replace('+',' ',$slug);
		$slug=str_replace(',',' ',$slug);
		$slug=str_replace('-',' ',$slug);
		$slug=str_replace('.',' ',$slug);
		$slug=str_replace('/',' ',$slug);
		$slug=str_replace(':',' ',$slug);
		$slug=str_replace(';',' ',$slug);
		$slug=str_replace('<',' ',$slug);
		$slug=str_replace('=',' ',$slug);
		$slug=str_replace('>',' ',$slug);
		$slug=str_replace('?',' ',$slug);
		$slug=str_replace('@',' ',$slug);
		$slug=str_replace('[',' ',$slug);
		$slug=str_replace(']',' ',$slug);
		$slug=str_replace('^',' ',$slug);
		$slug=str_replace('_',' ',$slug);
		$slug=str_replace('`',' ',$slug);
		$slug=str_replace('{',' ',$slug);
		$slug=str_replace('|',' ',$slug);
		$slug=str_replace('}',' ',$slug);
		$slug=str_replace('~',' ',$slug);
		$slug=str_replace('€',' ',$slug);
		$slug=str_replace('‚',' ',$slug);
		$slug=str_replace('ƒ',' ',$slug);
		$slug=str_replace('„',' ',$slug);
		$slug=str_replace('…',' ',$slug);
		$slug=str_replace('†',' ',$slug);
		$slug=str_replace('‡',' ',$slug);
		$slug=str_replace('ˆ',' ',$slug);
		$slug=str_replace('‰',' ',$slug);
		$slug=str_replace('Š',' ',$slug);
		$slug=str_replace('‹',' ',$slug);
		$slug=str_replace('Œ',' ',$slug);
		$slug=str_replace('Ž',' ',$slug);
		$slug=str_replace('‘',' ',$slug);
		$slug=str_replace('’',' ',$slug);
		$slug=str_replace('“',' ',$slug);
		$slug=str_replace('”',' ',$slug);
		$slug=str_replace('•',' ',$slug);
		$slug=str_replace('–',' ',$slug);
		$slug=str_replace('—',' ',$slug);
		$slug=str_replace('˜',' ',$slug);
		$slug=str_replace('™',' ',$slug);
		$slug=str_replace('š',' ',$slug);
		$slug=str_replace('›',' ',$slug);
		$slug=str_replace('œ',' ',$slug);
		$slug=str_replace('ž',' ',$slug);
		$slug=str_replace('¡',' ',$slug);
		$slug=str_replace('¢',' ',$slug);
		$slug=str_replace('£',' ',$slug);
		$slug=str_replace('¤',' ',$slug);
		$slug=str_replace('¥',' ',$slug);
		$slug=str_replace('¦',' ',$slug);
		$slug=str_replace('§',' ',$slug);
		$slug=str_replace('¨',' ',$slug);
		$slug=str_replace('©',' ',$slug);
		$slug=str_replace('ª',' ',$slug);
		$slug=str_replace('«',' ',$slug);
		$slug=str_replace('¬',' ',$slug);
		$slug=str_replace(' ',' ',$slug);
		$slug=str_replace('®',' ',$slug);
		$slug=str_replace('¯',' ',$slug);
		$slug=str_replace('°',' ',$slug);
		$slug=str_replace('±',' ',$slug);
		$slug=str_replace('²',' ',$slug);
		$slug=str_replace('³',' ',$slug);
		$slug=str_replace('´',' ',$slug);
		$slug=str_replace('µ',' ',$slug);
		$slug=str_replace('¶',' ',$slug);
		$slug=str_replace('·',' ',$slug);
		$slug=str_replace('¸',' ',$slug);
		$slug=str_replace('¹',' ',$slug);
		$slug=str_replace('º',' ',$slug);
		$slug=str_replace('»',' ',$slug);
		$slug=str_replace('¼',' ',$slug);
		$slug=str_replace('½',' ',$slug);
		$slug=str_replace('¾',' ',$slug);
		$slug=str_replace('¿',' ',$slug);
		$slug=str_replace('À','a',$slug);
		$slug=str_replace('Á','a',$slug);
		$slug=str_replace('Â','a',$slug);
		$slug=str_replace('Ã','a',$slug);
		$slug=str_replace('Ä','a',$slug);
		$slug=str_replace('Å','a',$slug);
		$slug=str_replace('Æ','a',$slug);
		$slug=str_replace('Ç','c',$slug);
		$slug=str_replace('È','e',$slug);
		$slug=str_replace('É','e',$slug);
		$slug=str_replace('Ê','e',$slug);
		$slug=str_replace('Ë','e',$slug);
		$slug=str_replace('Ì','i',$slug);
		$slug=str_replace('Í','i',$slug);
		$slug=str_replace('Î','i',$slug);
		$slug=str_replace('Ï','i',$slug);
		$slug=str_replace('Ð','d',$slug);
		$slug=str_replace('Ñ','n',$slug);
		$slug=str_replace('Ò','o',$slug);
		$slug=str_replace('Ó','o',$slug);
		$slug=str_replace('Ô','o',$slug);
		$slug=str_replace('Õ','o',$slug);
		$slug=str_replace('Ö','o',$slug);
		$slug=str_replace('×','x',$slug);
		$slug=str_replace('Ø','o',$slug);
		$slug=str_replace('Ù','u',$slug);
		$slug=str_replace('Ú','u',$slug);
		$slug=str_replace('Û','u',$slug);
		$slug=str_replace('Ü','u',$slug);
		$slug=str_replace('Ý','y',$slug);
		$slug=str_replace('Þ','a',$slug);
		$slug=str_replace('ß','b',$slug);
		$slug=str_replace('à','a',$slug);
		$slug=str_replace('á','a',$slug);
		$slug=str_replace('â','a',$slug);
		$slug=str_replace('ã','a',$slug);
		$slug=str_replace('ä','a',$slug);
		$slug=str_replace('å','a',$slug);
		$slug=str_replace('æ','a',$slug);
		$slug=str_replace('ç','c',$slug);
		$slug=str_replace('è','e',$slug);
		$slug=str_replace('é','e',$slug);
		$slug=str_replace('ê','e',$slug);
		$slug=str_replace('ë','e',$slug);
		$slug=str_replace('ì','i',$slug);
		$slug=str_replace('í','i',$slug);
		$slug=str_replace('î','i',$slug);
		$slug=str_replace('ï','i',$slug);
		$slug=str_replace('ð','o',$slug);
		$slug=str_replace('ñ','n',$slug);
		$slug=str_replace('ò','o',$slug);
		$slug=str_replace('ó','o',$slug);
		$slug=str_replace('ô','o',$slug);
		$slug=str_replace('õ','o',$slug);
		$slug=str_replace('ö','o',$slug);
		$slug=str_replace('÷',' ',$slug);
		$slug=str_replace('ø','o',$slug);
		$slug=str_replace('ù','u',$slug);
		$slug=str_replace('ú','u',$slug);
		$slug=str_replace('û','u',$slug);
		$slug=str_replace('ü','u',$slug);
		$slug=str_replace('ý','y',$slug);
		$slug=str_replace('þ',' ',$slug);
		$slug=str_replace('ÿ','y',$slug);
		$slug=str_replace('Ā','a',$slug);
		$slug=str_replace('ā','a',$slug);
		$slug=str_replace('Ă','a',$slug);
		$slug=str_replace('ă','a',$slug);
		$slug=str_replace('Ą','a',$slug);
		$slug=str_replace('ą','q',$slug);
		$slug=str_replace('Ć','c',$slug);
		$slug=str_replace('ć','c',$slug);
		$slug=str_replace('Ĉ','c',$slug);
		$slug=str_replace('ĉ','c',$slug);
		$slug=str_replace('Ċ','c',$slug);
		$slug=str_replace('ċ','c',$slug);
		$slug=str_replace('Č','c',$slug);
		$slug=str_replace('č','c',$slug);
		$slug=str_replace('Ď','d',$slug);
		$slug=str_replace('ď','d',$slug);
		$slug=str_replace('Đ','d',$slug);
		$slug=str_replace('đ','d',$slug);
		$slug=str_replace('Ē','e',$slug);
		$slug=str_replace('ē','e',$slug);
		$slug=str_replace('Ĕ','e',$slug);
		$slug=str_replace('ĕ','e',$slug);
		$slug=str_replace('Ė','e',$slug);
		$slug=str_replace('ė','e',$slug);
		$slug=str_replace('Ę','e',$slug);
		$slug=str_replace('ę','e',$slug);
		$slug=str_replace('Ě','e',$slug);
		$slug=str_replace('ě','e',$slug);
		$slug=str_replace('Ĝ','g',$slug);
		$slug=str_replace('ĝ','g',$slug);
		$slug=str_replace('Ğ','g',$slug);
		$slug=str_replace('ğ','g',$slug);
		$slug=str_replace('Ġ','g',$slug);
		$slug=str_replace('ġ','g',$slug);
		$slug=str_replace('Ģ','g',$slug);
		$slug=str_replace('ģ','g',$slug);
		$slug=str_replace('Ĥ','h',$slug);
		$slug=str_replace('ĥ','h',$slug);
		$slug=str_replace('Ħ','h',$slug);
		$slug=str_replace('ħ','h',$slug);
		$slug=str_replace('Ĩ','i',$slug);
		$slug=str_replace('ĩ','i',$slug);
		$slug=str_replace('Ī','i',$slug);
		$slug=str_replace('ī','i',$slug);
		$slug=str_replace('Ĭ','i',$slug);
		$slug=str_replace('ĭ','i',$slug);
		$slug=str_replace('Į','i',$slug);
		$slug=str_replace('į','i',$slug);
		$slug=str_replace('İ','i',$slug);
		$slug=str_replace('ı','i',$slug);
		$slug=str_replace('Ĳ','i',$slug);
		$slug=str_replace('ĳ','j',$slug);
		$slug=str_replace('Ĵ','j',$slug);
		$slug=str_replace('ĵ','j',$slug);
		$slug=str_replace('Ķ','k',$slug);
		$slug=str_replace('ķ','k',$slug);
		$slug=str_replace('ĸ','k',$slug);
		$slug=str_replace('Ĺ','l',$slug);
		$slug=str_replace('ĺ','l',$slug);
		$slug=str_replace('Ļ','l',$slug);
		$slug=str_replace('ļ','l',$slug);
		$slug=str_replace('Ľ','l',$slug);
		$slug=str_replace('ľ','l',$slug);
		$slug=str_replace('Ŀ','l',$slug);
		$slug=str_replace('ŀ','l',$slug);
		$slug=str_replace('Ł','l',$slug);
		$slug=str_replace('ł','l',$slug);
		$slug=str_replace('Ń','n',$slug);
		$slug=str_replace('ń','n',$slug);
		$slug=str_replace('Ņ','n',$slug);
		$slug=str_replace('ņ','n',$slug);
		$slug=str_replace('Ň','n',$slug);
		$slug=str_replace('ň','n',$slug);
		$slug=str_replace('ŉ','n',$slug);
		$slug=str_replace('Ŋ','n',$slug);
		$slug=str_replace('ŋ','n',$slug);
		$slug=str_replace('Ō','o',$slug);
		$slug=str_replace('ō','o',$slug);
		$slug=str_replace('Ŏ','o',$slug);
		$slug=str_replace('ŏ','o',$slug);
		$slug=str_replace('Ő','o',$slug);
		$slug=str_replace('ő','o',$slug);
		$slug=str_replace('Œ','o',$slug);
		$slug=str_replace('œ','o',$slug);
		$slug=str_replace('Ŕ','r',$slug);
		$slug=str_replace('ŕ','r',$slug);
		$slug=str_replace('Ŗ','r',$slug);
		$slug=str_replace('ŗ','r',$slug);
		$slug=str_replace('Ř','r',$slug);
		$slug=str_replace('ř','r',$slug);
		$slug=str_replace('Ś','s',$slug);
		$slug=str_replace('ś','s',$slug);
		$slug=str_replace('Ŝ','s',$slug);
		$slug=str_replace('ŝ','s',$slug);
		$slug=str_replace('Ş','s',$slug);
		$slug=str_replace('ş','s',$slug);
		$slug=str_replace('Š','s',$slug);
		$slug=str_replace('š','s',$slug);
		$slug=str_replace('Ţ','t',$slug);
		$slug=str_replace('ţ','t',$slug);
		$slug=str_replace('Ť','t',$slug);
		$slug=str_replace('ť','t',$slug);
		$slug=str_replace('Ŧ','t',$slug);
		$slug=str_replace('ŧ','t',$slug);
		$slug=str_replace('Ũ','u',$slug);
		$slug=str_replace('ũ','u',$slug);
		$slug=str_replace('Ū','u',$slug);
		$slug=str_replace('ū','u',$slug);
		$slug=str_replace('Ŭ','u',$slug);
		$slug=str_replace('ŭ','u',$slug);
		$slug=str_replace('Ů','u',$slug);
		$slug=str_replace('ů','u',$slug);
		$slug=str_replace('Ű','u',$slug);
		$slug=str_replace('ű','u',$slug);
		$slug=str_replace('Ų','v',$slug);
		$slug=str_replace('ų','v',$slug);
		$slug=str_replace('Ŵ','w',$slug);
		$slug=str_replace('ŵ','w',$slug);
		$slug=str_replace('Ŷ','y',$slug);
		$slug=str_replace('ŷ','y',$slug);
		$slug=str_replace('Ÿ','y',$slug);
		$slug=str_replace('Ź','z',$slug);
		$slug=str_replace('ź','z',$slug);
		$slug=str_replace('Ż','z',$slug);
		$slug=str_replace('ż','z',$slug);
		$slug=str_replace('Ž','z',$slug);
		$slug=str_replace('ž','z',$slug);
		$slug=str_replace('ſ',' ',$slug);
		$slug=str_replace('ƀ','b',$slug);
		$slug=str_replace('Ɓ','b',$slug);
		$slug=str_replace('Ƃ','b',$slug);
		$slug=str_replace('ƃ','b',$slug);
		$slug=str_replace('Ƅ','b',$slug);
		$slug=str_replace('ƅ','b',$slug);
		$slug=str_replace('Ɔ','c',$slug);
		$slug=str_replace('Ƈ','c',$slug);
		$slug=str_replace('ƈ','c',$slug);
		$slug=str_replace('Ɖ','d',$slug);
		$slug=str_replace('Ɗ','d',$slug);
		$slug=str_replace('Ǎ','a',$slug);
		$slug=str_replace('ǎ','a',$slug);
		$slug=str_replace('Ǐ','i',$slug);
		$slug=str_replace('ǐ','i',$slug);
		$slug=str_replace('Ǒ','o',$slug);
		$slug=str_replace('ǒ','o',$slug);
		$slug=str_replace('Ǔ','u',$slug);
		$slug=str_replace('ǔ','u',$slug);
		$slug=str_replace('Ǖ','u',$slug);
		$slug=str_replace('ǖ','u',$slug);
		$slug=str_replace('Ǘ','u',$slug);
		$slug=str_replace('ǘ','u',$slug);
		$slug=str_replace('Ǚ','u',$slug);
		$slug=str_replace('ǚ','u',$slug);
		$slug=str_replace('Ǜ','u',$slug);
		$slug=str_replace('ǜ','u',$slug);
		$slug=str_replace('ǝ','e',$slug);
		$slug=str_replace('Ǟ','a',$slug);
		$slug=str_replace('ǟ','a',$slug);
		$slug=str_replace('Ǡ','a',$slug);
		$slug=str_replace('ǡ','a',$slug);
		$slug=str_replace('Ǣ','a',$slug);
		$slug=str_replace('ǣ','a',$slug);
		$slug=str_replace('Ǥ','g',$slug);
		$slug=str_replace('ǥ','g',$slug);
		$slug=str_replace('Ǧ','g',$slug);
		$slug=str_replace('ǧ','g',$slug);
		$slug=str_replace('Ǩ','k',$slug);
		$slug=str_replace('ǩ','k',$slug);
		$slug=str_replace('Ǫ','o',$slug);
		$slug=str_replace('ǫ','o',$slug);
		$slug=str_replace('Ǭ','o',$slug);
		$slug=str_replace('ǭ','o',$slug);
		$slug=str_replace('ǰ','j',$slug);
		$slug=str_replace('Ǵ','g',$slug);
		$slug=str_replace('ǵ','g',$slug);
		$slug=str_replace('Ƿ','p',$slug);
		$slug=str_replace('Ǹ','n',$slug);
		$slug=str_replace('ǹ','n',$slug);
		$slug=str_replace('Ǻ','a',$slug);
		$slug=str_replace('ǻ','a',$slug);
		$slug=str_replace('Ǽ','a',$slug);
		$slug=str_replace('ǽ','a',$slug);
		$slug=str_replace('Ǿ','o',$slug);
		$slug=str_replace('ǿ','o',$slug);
		$slug=str_replace('Ȁ','a',$slug);
		$slug=str_replace('ȁ','a',$slug);
		$slug=str_replace('Ȃ','a',$slug);
		$slug=str_replace('ȃ','a',$slug);
		$slug=str_replace('Ȅ','e',$slug);
		$slug=str_replace('ȅ','e',$slug);
		$slug=str_replace('Ȇ','e',$slug);
		$slug=str_replace('ȇ','e',$slug);
		$slug=str_replace('Ȉ','i',$slug);
		$slug=str_replace('ȉ','i',$slug);
		$slug=str_replace('Ȋ','i',$slug);
		$slug=str_replace('ȋ','i',$slug);
		$slug=str_replace('Ȍ','o',$slug);
		$slug=str_replace('ȍ','o',$slug);
		$slug=str_replace('Ȏ','o',$slug);
		$slug=str_replace('ȏ','o',$slug);
		$slug=str_replace('Ȑ','r',$slug);
		$slug=str_replace('ȑ','r',$slug);
		$slug=str_replace('Ȓ','r',$slug);
		$slug=str_replace('ȓ','r',$slug);
		$slug=str_replace('Ȕ','u',$slug);
		$slug=str_replace('ȕ','u',$slug);
		$slug=str_replace('Ȗ','u',$slug);
		$slug=str_replace('ȗ','u',$slug);
		$slug=str_replace('Ȧ','a',$slug);
		$slug=str_replace('ȧ','a',$slug);
		$slug=str_replace('Ȩ','e',$slug);
		$slug=str_replace('ȩ','e',$slug);
		$slug=str_replace('Ȫ','o',$slug);
		$slug=str_replace('ȫ','o',$slug);
		$slug=str_replace('Ȭ','o',$slug);
		$slug=str_replace('ȭ','o',$slug);
		$slug=str_replace('Ȯ','o',$slug);
		$slug=str_replace('ȯ','o',$slug);
		$slug=str_replace('Ȱ','o',$slug);
		$slug=str_replace('ȱ','o',$slug);
		$slug=str_replace('Ȳ','y',$slug);
		$slug=str_replace('ȳ','y',$slug);
		$slug=str_replace('  ',' ',$slug);
		$slug=preg_replace('/\s+/', ' ', $slug);
		$slug=trim($slug);
		$slug = stripslashes($slug);
		return $slug;
	}


 	// Function to eliminate any caracter different to letters
  // and numbers to send the SMS messages
	public function slug_SMS($label) {
		//$slug=strtolower($label);
    $slug=$label;
		$slug=str_replace('Æ','A',$slug);
		$slug=str_replace('À','A',$slug);
		$slug=str_replace('Á','A',$slug);
		$slug=str_replace('Â','A',$slug);
		$slug=str_replace('Ã','A',$slug);
		$slug=str_replace('Ä','A',$slug);
		$slug=str_replace('Å','A',$slug);
		$slug=str_replace('à','a',$slug);
		$slug=str_replace('á','a',$slug);
		$slug=str_replace('â','a',$slug);
		$slug=str_replace('ã','a',$slug);
		$slug=str_replace('ä','a',$slug);
		$slug=str_replace('å','a',$slug);
		$slug=str_replace('Ò','O',$slug);
		$slug=str_replace('Ó','O',$slug);
		$slug=str_replace('Ô','O',$slug);
		$slug=str_replace('Õ','O',$slug);
		$slug=str_replace('Ö','O',$slug);
		$slug=str_replace('Ø','O',$slug);
		$slug=str_replace('ò','o',$slug);
		$slug=str_replace('ó','o',$slug);
		$slug=str_replace('ô','o',$slug);
		$slug=str_replace('õ','o',$slug);
		$slug=str_replace('ö','o',$slug);
		$slug=str_replace('ø','o',$slug);
		$slug=str_replace('È','E',$slug);
		$slug=str_replace('É','E',$slug);
		$slug=str_replace('Ê','E',$slug);
		$slug=str_replace('Ë','E',$slug);
		$slug=str_replace('è','e',$slug);
		$slug=str_replace('é','e',$slug);
		$slug=str_replace('ê','e',$slug);
		$slug=str_replace('ë','e',$slug);
		$slug=str_replace('Ç','C',$slug);
		$slug=str_replace('ç','c',$slug);
		$slug=str_replace('Ì','I',$slug);
		$slug=str_replace('Í','I',$slug);
		$slug=str_replace('Î','I',$slug);
		$slug=str_replace('Ï','I',$slug);
		$slug=str_replace('ì','i',$slug);
		$slug=str_replace('í','i',$slug);
		$slug=str_replace('î','i',$slug);
		$slug=str_replace('ï','i',$slug);
		$slug=str_replace('Ù','U',$slug);
		$slug=str_replace('Ú','U',$slug);
		$slug=str_replace('Û','U',$slug);
		$slug=str_replace('Ü','U',$slug);
		$slug=str_replace('ù','u',$slug);
		$slug=str_replace('ú','u',$slug);
		$slug=str_replace('û','u',$slug);
		$slug=str_replace('ü','u',$slug);
		$slug=str_replace('ÿ','y',$slug);
		$slug=str_replace('Ñ','N',$slug);
		$slug=str_replace('ñ','n',$slug);
		$slug=str_replace('Č','C',$slug);
		$slug=str_replace('é','e',$slug);
		$slug=str_replace('ß','B',$slug);
		$slug=str_replace('^',' ',$slug);
		$slug=str_replace('`',' ',$slug);
		$slug=str_replace('{',' ',$slug);
		$slug=str_replace('|',' ',$slug);
		$slug=str_replace('}',' ',$slug);
		$slug=str_replace('~',' ',$slug);
		$slug=str_replace('€',' ',$slug);
//		$slug=str_replace('%',' ',$slug);
		$slug=str_replace('ƒ',' ',$slug);
		$slug=str_replace('„',' ',$slug);
		$slug=str_replace('…',' ',$slug);
		$slug=str_replace('†',' ',$slug);
		$slug=str_replace('‡',' ',$slug);
		$slug=str_replace('ˆ',' ',$slug);
		$slug=str_replace('‰',' ',$slug);
		$slug=str_replace('Š',' ',$slug);
		$slug=str_replace('‹',' ',$slug);
		$slug=str_replace('Œ',' ',$slug);
		$slug=str_replace('Ž',' ',$slug);
		$slug=str_replace('‘',' ',$slug);
		$slug=str_replace('’',' ',$slug);
		$slug=str_replace('“',' ',$slug);
		$slug=str_replace('”',' ',$slug);
		$slug=str_replace('•',' ',$slug);
		$slug=str_replace('˜',' ',$slug);
		$slug=str_replace('™',' ',$slug);
		$slug=str_replace('š',' ',$slug);
		$slug=str_replace('›',' ',$slug);
		$slug=str_replace('œ',' ',$slug);
		$slug=str_replace('ž',' ',$slug);
		$slug=str_replace('¡',' ',$slug);
		$slug=str_replace('¢',' ',$slug);
		$slug=str_replace('£',' ',$slug);
		$slug=str_replace('¤',' ',$slug);
		$slug=str_replace('¥',' ',$slug);
		$slug=str_replace('¦',' ',$slug);
		$slug=str_replace('§',' ',$slug);
		$slug=str_replace('¨',' ',$slug);
		$slug=str_replace('©',' ',$slug);
		$slug=str_replace('ª',' ',$slug);
		$slug=str_replace('«',' ',$slug);
		$slug=str_replace('¬',' ',$slug);
		$slug=str_replace(' ',' ',$slug);
		$slug=str_replace('®',' ',$slug);
		$slug=str_replace('¯',' ',$slug);
		$slug=str_replace('°',' ',$slug);
		$slug=str_replace('±',' ',$slug);
		$slug=str_replace('²',' ',$slug);
		$slug=str_replace('³',' ',$slug);
		$slug=str_replace('´',' ',$slug);
		$slug=str_replace('µ',' ',$slug);
		$slug=str_replace('¶',' ',$slug);
		$slug=str_replace('·',' ',$slug);
		$slug=str_replace('¸',' ',$slug);
		$slug=str_replace('¹',' ',$slug);
		$slug=str_replace('º',' ',$slug);
		$slug=str_replace('»',' ',$slug);
		$slug=str_replace('¼',' ',$slug);
		$slug=str_replace('½',' ',$slug);
		$slug=str_replace('¾',' ',$slug);
		$slug=str_replace('¿',' ',$slug);
		$slug=str_replace('×','x',$slug);
		$slug=str_replace('Þ','a',$slug);
		$slug=str_replace('ß','B',$slug);
		$slug=str_replace('à','a',$slug);
		$slug=str_replace('á','a',$slug);
		$slug=str_replace('â','a',$slug);
		$slug=str_replace('ã','a',$slug);
		$slug=str_replace('ä','a',$slug);
		$slug=str_replace('å','a',$slug);
		$slug=str_replace('æ','a',$slug);
		$slug=str_replace('ç','c',$slug);
		$slug=str_replace('è','e',$slug);
		$slug=str_replace('é','e',$slug);
		$slug=str_replace('ê','e',$slug);
		$slug=str_replace('ë','e',$slug);
		$slug=str_replace('ì','i',$slug);
		$slug=str_replace('í','i',$slug);
		$slug=str_replace('î','i',$slug);
		$slug=str_replace('ï','i',$slug);
		$slug=str_replace('ð','o',$slug);
		$slug=str_replace('ñ','n',$slug);
		$slug=str_replace('ò','o',$slug);
		$slug=str_replace('ó','o',$slug);
		$slug=str_replace('ô','o',$slug);
		$slug=str_replace('õ','o',$slug);
		$slug=str_replace('ö','o',$slug);
		$slug=str_replace('ø','o',$slug);
		$slug=str_replace('ù','u',$slug);
		$slug=str_replace('ú','u',$slug);
		$slug=str_replace('û','u',$slug);
		$slug=str_replace('ü','u',$slug);
		$slug=str_replace('ý','y',$slug);
		$slug=str_replace('þ',' ',$slug);
		$slug=str_replace('ÿ','y',$slug);
		$slug=str_replace('Ā','A',$slug);
		$slug=str_replace('ā','a',$slug);
		$slug=str_replace('Ă','A',$slug);
		$slug=str_replace('ă','a',$slug);
		$slug=str_replace('Ą','A',$slug);
		$slug=str_replace('ą','q',$slug);
		$slug=str_replace('Ć','C',$slug);
		$slug=str_replace('ć','c',$slug);
		$slug=str_replace('Ĉ','C',$slug);
		$slug=str_replace('ĉ','c',$slug);
		$slug=str_replace('Ċ','C',$slug);
		$slug=str_replace('ċ','c',$slug);
		$slug=str_replace('Č','C',$slug);
		$slug=str_replace('č','c',$slug);
		$slug=str_replace('Ď','D',$slug);
		$slug=str_replace('ď','d',$slug);
		$slug=str_replace('Đ','D',$slug);
		$slug=str_replace('đ','d',$slug);
		$slug=str_replace('Ē','E',$slug);
		$slug=str_replace('ē','e',$slug);
		$slug=str_replace('Ĕ','E',$slug);
		$slug=str_replace('ĕ','e',$slug);
		$slug=str_replace('Ė','E',$slug);
		$slug=str_replace('ė','e',$slug);
		$slug=str_replace('Ę','E',$slug);
		$slug=str_replace('ę','e',$slug);
		$slug=str_replace('Ě','E',$slug);
		$slug=str_replace('ě','e',$slug);
		$slug=str_replace('Ĝ','G',$slug);
		$slug=str_replace('ĝ','g',$slug);
		$slug=str_replace('Ğ','G',$slug);
		$slug=str_replace('ğ','g',$slug);
		$slug=str_replace('Ġ','g',$slug);
		$slug=str_replace('ġ','g',$slug);
		$slug=str_replace('Ģ','G',$slug);
		$slug=str_replace('ģ','g',$slug);
		$slug=str_replace('Ĥ','H',$slug);
		$slug=str_replace('ĥ','h',$slug);
		$slug=str_replace('Ħ','h',$slug);
		$slug=str_replace('ħ','h',$slug);
		$slug=str_replace('Ĩ','I',$slug);
		$slug=str_replace('ĩ','i',$slug);
		$slug=str_replace('Ī','I',$slug);
		$slug=str_replace('ī','i',$slug);
		$slug=str_replace('Ĭ','I',$slug);
		$slug=str_replace('ĭ','i',$slug);
		$slug=str_replace('Į','I',$slug);
		$slug=str_replace('į','i',$slug);
		$slug=str_replace('İ','I',$slug);
		$slug=str_replace('ı','i',$slug);
		$slug=str_replace('Ĳ','i',$slug);
		$slug=str_replace('ĳ','j',$slug);
		$slug=str_replace('Ĵ','J',$slug);
		$slug=str_replace('ĵ','J',$slug);
		$slug=str_replace('Ķ','K',$slug);
		$slug=str_replace('ķ','k',$slug);
		$slug=str_replace('ĸ','k',$slug);
		$slug=str_replace('Ĺ','L',$slug);
		$slug=str_replace('ĺ','l',$slug);
		$slug=str_replace('Ļ','L',$slug);
		$slug=str_replace('ļ','l',$slug);
		$slug=str_replace('Ľ','L',$slug);
		$slug=str_replace('ľ','l',$slug);
		$slug=str_replace('Ŀ','L',$slug);
		$slug=str_replace('ŀ','l',$slug);
		$slug=str_replace('Ł','L',$slug);
		$slug=str_replace('ł','l',$slug);
		$slug=str_replace('Ń','N',$slug);
		$slug=str_replace('ń','n',$slug);
		$slug=str_replace('Ņ','N',$slug);
		$slug=str_replace('ņ','n',$slug);
		$slug=str_replace('Ň','N',$slug);
		$slug=str_replace('ň','n',$slug);
		$slug=str_replace('ŉ','n',$slug);
		$slug=str_replace('Ŋ','N',$slug);
		$slug=str_replace('ŋ','n',$slug);
		$slug=str_replace('Ō','O',$slug);
		$slug=str_replace('ō','o',$slug);
		$slug=str_replace('Ŏ','O',$slug);
		$slug=str_replace('ŏ','o',$slug);
		$slug=str_replace('Ő','O',$slug);
		$slug=str_replace('ő','o',$slug);
		$slug=str_replace('Œ','O',$slug);
		$slug=str_replace('œ','o',$slug);
		$slug=str_replace('Ŕ','R',$slug);
		$slug=str_replace('ŕ','r',$slug);
		$slug=str_replace('Ŗ','R',$slug);
		$slug=str_replace('ŗ','r',$slug);
		$slug=str_replace('Ř','R',$slug);
		$slug=str_replace('ř','r',$slug);
//		$slug=str_replace('$','S',$slug);
		$slug=str_replace('Ś','S',$slug);
		$slug=str_replace('ś','s',$slug);
		$slug=str_replace('Ŝ','S',$slug);
		$slug=str_replace('ŝ','s',$slug);
		$slug=str_replace('Ş','S',$slug);
		$slug=str_replace('ş','s',$slug);
		$slug=str_replace('Š','S',$slug);
		$slug=str_replace('š','s',$slug);
		$slug=str_replace('Ţ','T',$slug);
		$slug=str_replace('ţ','t',$slug);
		$slug=str_replace('Ť','T',$slug);
		$slug=str_replace('ť','t',$slug);
		$slug=str_replace('Ŧ','T',$slug);
		$slug=str_replace('ŧ','t',$slug);
		$slug=str_replace('Ũ','U',$slug);
		$slug=str_replace('ũ','u',$slug);
		$slug=str_replace('Ū','U',$slug);
		$slug=str_replace('ū','u',$slug);
		$slug=str_replace('Ŭ','U',$slug);
		$slug=str_replace('ŭ','u',$slug);
		$slug=str_replace('Ů','U',$slug);
		$slug=str_replace('ů','u',$slug);
		$slug=str_replace('Ű','U',$slug);
		$slug=str_replace('ű','u',$slug);
		$slug=str_replace('Ų','U',$slug);
		$slug=str_replace('ų','v',$slug);
		$slug=str_replace('Ŵ','W',$slug);
		$slug=str_replace('ŵ','w',$slug);
		$slug=str_replace('Ŷ','y',$slug);
		$slug=str_replace('ŷ','y',$slug);
		$slug=str_replace('Ÿ','y',$slug);
		$slug=str_replace('Ź','Z',$slug);
		$slug=str_replace('ź','z',$slug);
		$slug=str_replace('Ż','Z',$slug);
		$slug=str_replace('ż','z',$slug);
		$slug=str_replace('Ž','z',$slug);
		$slug=str_replace('ž','z',$slug);
		$slug=str_replace('ſ',' ',$slug);
		$slug=str_replace('ƀ','b',$slug);
		$slug=str_replace('Ɓ','B',$slug);
		$slug=str_replace('Ƃ','b',$slug);
		$slug=str_replace('ƃ','b',$slug);
		$slug=str_replace('Ƅ','b',$slug);
		$slug=str_replace('ƅ','b',$slug);
		$slug=str_replace('Ɔ','c',$slug);
		$slug=str_replace('Ƈ','C',$slug);
		$slug=str_replace('ƈ','c',$slug);
		$slug=str_replace('Ɖ','d',$slug);
		$slug=str_replace('Ɗ','D',$slug);
		$slug=str_replace('Ǎ','A',$slug);
		$slug=str_replace('ǎ','a',$slug);
		$slug=str_replace('Ǐ','I',$slug);
		$slug=str_replace('ǐ','i',$slug);
		$slug=str_replace('Ǒ','O',$slug);
		$slug=str_replace('ǒ','o',$slug);
		$slug=str_replace('Ǔ','U',$slug);
		$slug=str_replace('ǔ','u',$slug);
		$slug=str_replace('Ǖ','U',$slug);
		$slug=str_replace('ǖ','u',$slug);
		$slug=str_replace('Ǘ','U',$slug);
		$slug=str_replace('ǘ','u',$slug);
		$slug=str_replace('Ǚ','U',$slug);
		$slug=str_replace('ǚ','u',$slug);
		$slug=str_replace('Ǜ','U',$slug);
		$slug=str_replace('ǜ','u',$slug);
		$slug=str_replace('ǝ','e',$slug);
		$slug=str_replace('Ǟ','A',$slug);
		$slug=str_replace('ǟ','a',$slug);
		$slug=str_replace('Ǡ','A',$slug);
		$slug=str_replace('ǡ','a',$slug);
		$slug=str_replace('Ǣ','A',$slug);
		$slug=str_replace('ǣ','a',$slug);
		$slug=str_replace('Ǥ','G',$slug);
		$slug=str_replace('ǥ','g',$slug);
		$slug=str_replace('Ǧ','G',$slug);
		$slug=str_replace('ǧ','g',$slug);
		$slug=str_replace('Ǩ','K',$slug);
		$slug=str_replace('ǩ','k',$slug);
		$slug=str_replace('Ǫ','O',$slug);
		$slug=str_replace('ǫ','o',$slug);
		$slug=str_replace('Ǭ','O',$slug);
		$slug=str_replace('ǭ','o',$slug);
		$slug=str_replace('ǰ','j',$slug);
		$slug=str_replace('Ǵ','G',$slug);
		$slug=str_replace('ǵ','g',$slug);
		$slug=str_replace('Ƿ','P',$slug);
		$slug=str_replace('Ǹ','N',$slug);
		$slug=str_replace('ǹ','n',$slug);
		$slug=str_replace('Ǻ','A',$slug);
		$slug=str_replace('ǻ','a',$slug);
		$slug=str_replace('Ǽ','A',$slug);
		$slug=str_replace('ǽ','a',$slug);
		$slug=str_replace('Ǿ','o',$slug);
		$slug=str_replace('ǿ','O',$slug);
		$slug=str_replace('Ȁ','A',$slug);
		$slug=str_replace('ȁ','a',$slug);
		$slug=str_replace('Ȃ','A',$slug);
		$slug=str_replace('ȃ','a',$slug);
		$slug=str_replace('Ȅ','E',$slug);
		$slug=str_replace('ȅ','e',$slug);
		$slug=str_replace('Ȇ','E',$slug);
		$slug=str_replace('ȇ','e',$slug);
		$slug=str_replace('Ȉ','I',$slug);
		$slug=str_replace('ȉ','i',$slug);
		$slug=str_replace('Ȋ','I',$slug);
		$slug=str_replace('ȋ','i',$slug);
		$slug=str_replace('Ȍ','O',$slug);
		$slug=str_replace('ȍ','o',$slug);
		$slug=str_replace('Ȏ','O',$slug);
		$slug=str_replace('ȏ','o',$slug);
		$slug=str_replace('Ȑ','R',$slug);
		$slug=str_replace('ȑ','r',$slug);
		$slug=str_replace('Ȓ','R',$slug);
		$slug=str_replace('ȓ','r',$slug);
		$slug=str_replace('Ȕ','U',$slug);
		$slug=str_replace('ȕ','u',$slug);
		$slug=str_replace('Ȗ','U',$slug);
		$slug=str_replace('ȗ','u',$slug);
		$slug=str_replace('Ȧ','A',$slug);
		$slug=str_replace('ȧ','a',$slug);
		$slug=str_replace('Ȩ','E',$slug);
		$slug=str_replace('ȩ','e',$slug);
		$slug=str_replace('Ȫ','O',$slug);
		$slug=str_replace('ȫ','o',$slug);
		$slug=str_replace('Ȭ','O',$slug);
		$slug=str_replace('ȭ','o',$slug);
		$slug=str_replace('Ȯ','O',$slug);
		$slug=str_replace('ȯ','o',$slug);
		$slug=str_replace('Ȱ','O',$slug);
		$slug=str_replace('ȱ','o',$slug);
		$slug=str_replace('Ȳ','y',$slug);
		$slug=str_replace('ȳ','y',$slug);
		$slug=str_replace('  ',' ',$slug);
		$slug=preg_replace('/\s+/', ' ', $slug);
		$slug=trim($slug);
		$slug = stripslashes($slug);
		return $slug;
	}


    public function send_mail($email_to, $email_subject, $message, $email_from = "") {
    include_once "Mail.php";
    include_once ('Mail/mime.php');

    $email_from = empty($email_from) ? "suporte@torpedocerto.com.br" : $email_from;
    $host       = "imap.alwaysdata.com";
    $username   = "suporte@torpedocerto.com.br";
    $password   = "sucesso";

    $headerss = array(
        'From'          => $email_from,
        'To'            => $email_to,
        'Subject'       => $email_subject,
        'charset'       => 'utf-8',
        'content_type'  => 'text/plain',
        'MIME-Version'  => '1.0');

    $message1 = new Mail_mime();
    $message1->setTXTBody($message);

    $mimeparams=array();
    $mimeparams['text_encoding']="7bit";
    $mimeparams['text_charset']="UTF-8";
    $mimeparams['head_charset']="UTF-8";

    $body = $message1->get($mimeparams);
    $headers = $message1->headers($headerss);

    $smtp = Mail::factory('smtp',
                    array('host' => $host,
                        'auth' => true,
                        'username' => $username,
                        'password' => $password));

    $mail = $smtp->send($email_to, $headers, $body);
    if (PEAR::isError($mail)) {
      return false;
    }
    else {
      return true;
    }
    }


  
} //end class